services:
  offers.listener.personal_data_ui:
    class: WEM\OffersBundle\Hooks\PersonalDataManager\UiHook
    arguments:
      $translator: '@contao.translation.translator'
      $csrfTokenManager: '@contao.csrf.token_manager'
      $csrfTokenName: '%contao.csrf_token_name%'
      $personalDataManagerUi: '@wem.personal_data_manager.service.personal_data_manager_ui'
    public: true